apiVersion: dbaoperator.app-sre.redhat.com/v1alpha1
kind: ManagedDatabase
metadata:
  name: quay-production-mysql
spec:
  connection:
    dsnSecret: quayiocreds-mysql
  migrationEngine: alembic
  desiredSchemaVersion: v3
  hintsEngine:
    enabled: true
    largetableRowsThreshold: 1000000