apiVersion: dbaoperator.app-sre.redhat.com/v1alpha1
kind: DatabaseMigration
metadata:
  name: v2-phase2-backfill
spec:
  previous: v1-phase1-add-new-column
  migrationContainerSpec: 
    name: v2-phase2-backfill
    image: quay.io/quaymigrations/v2
    command: ["alembic", "migrate", "v1"]
  scalable: true
