apiVersion: dbaoperator.app-sre.redhat.com/v1alpha1
kind: DatabaseMigration
metadata:
  name: v2
spec:
  previous: v1
  migrationContainerSpec: 
    name: v2-phase2-backfill
    image: quay.io/quaymigrations/test
    command: ["python", "migration.py", "--write_version", "v2"]
  scalable: true
