apiVersion: apps/v1
kind: Deployment
metadata:
  name: dba-operator
  labels:
    app: dba-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dba-operator
  template:
    metadata:
      labels:
        app: dba-operator
    spec:
      containers:
      - name: dba-operator
        image: quay.io/app-sre/dba-operator:v0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dba-operator
spec:
  selector:
    app: dba-operator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
