apiVersion: v1
kind: Service
metadata:
  name: prom-pushgateway-debug
spec:
  selector:
    app: pushgateway
  type: NodePort
  ports:
    - protocol: TCP
      port: 9091
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-debug
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_DATABASE
          value: quay
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-debug
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
