apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: manageddatabases.dbaoperator.app-sre.redhat.com
spec:
  group: dbaoperator.app-sre.redhat.com
  names:
    kind: ManagedDatabase
    listKind: ManagedDatabaseList
    plural: manageddatabases
    singular: manageddatabase
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
